name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: dataroadinc/github-actions/.github/workflows/cargo-crate-ci.yml@main
    with:
      crate-name: cargo-fmt-toml
      kind: binary
    secrets: inherit
